# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo.yml#L161
seed: 42

n_timesteps: !!float 5e8
policy: 'MlpPolicy'
batch_size: 12288
n_steps: 12
gamma: 0.99
gae_lambda: 0.95
n_epochs: 5
ent_coef: 0.01
sde_sample_freq: 4
max_grad_norm: 0.5
vf_coef: 1.0
learning_rate: lin_5e-4
use_sde: False
clip_range: 0.2
device: "cuda:0"
mixture_coeff: 0.0
policy_kwargs: "dict(
                  log_std_init=0,
                  ortho_init=True,
                  activation_fn=nn.ELU,
                  net_arch=[512,256,128],
                )"
student_policy_kwargs: "dict(
                  log_std_init=0,
                  ortho_init=True,
                  activation_fn=nn.ELU,
                  net_arch=[512,256,128],
                  lstm_hidden_size=128
                )"
