[build-system]
requires = ["setuptools", "wheel", "toml"]
build-backend = "setuptools.build_meta"
[tool.pyrefly]
search-path = [
    "../source/isaaclab/isaaclab",
    "../source/isaaclab_assets",
    "../source/isaaclab_rl",
    "../source/isaaclab_mimic",
    "../source/isaaclab_tasks",
]
